onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  '@prisma/generator-helper': $prisma
  '@prisma/internals': $prisma
