overrides:
  "@prisma/generator-helper": "$prisma"
  "@prisma/internals": "$prisma"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - simple-git-hooks
  - unrs-resolver
